// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oracle/v1/oracle.proto

package packet

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ResolveStatus encodes the status of an oracle request.
type ResolveStatus int32

const (
	// Open - the request is not yet resolved.
	RESOLVE_STATUS_OPEN ResolveStatus = 0
	// Success - the request has been resolved successfully with no errors.
	RESOLVE_STATUS_SUCCESS ResolveStatus = 1
	// Failure - an error occured during the request's resolve call.
	RESOLVE_STATUS_FAILURE ResolveStatus = 2
	// Expired - the request does not get enough reports from validator within the
	// timeframe.
	RESOLVE_STATUS_EXPIRED ResolveStatus = 3
)

var ResolveStatus_name = map[int32]string{
	0: "RESOLVE_STATUS_OPEN_UNSPECIFIED",
	1: "RESOLVE_STATUS_SUCCESS",
	2: "RESOLVE_STATUS_FAILURE",
	3: "RESOLVE_STATUS_EXPIRED",
}

var ResolveStatus_value = map[string]int32{
	"RESOLVE_STATUS_OPEN_UNSPECIFIED": 0,
	"RESOLVE_STATUS_SUCCESS":          1,
	"RESOLVE_STATUS_FAILURE":          2,
	"RESOLVE_STATUS_EXPIRED":          3,
}

func (x ResolveStatus) String() string {
	return proto.EnumName(ResolveStatus_name, int32(x))
}

func (ResolveStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_652b57db11528d07, []int{0}
}

// OracleRequestPacketData encodes an oracle request sent from other blockchains
// to BandChain.
type OracleRequestPacketData struct {
	// ClientID is the unique identifier of this oracle request, as specified by
	// the client. This same unique ID will be sent back to the requester with the
	// oracle response.
	ClientID string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// OracleScriptID is the unique identifier of the oracle script to be
	// executed.
	OracleScriptID uint64 `protobuf:"varint,2,opt,name=oracle_script_id,json=oracleScriptId,proto3,casttype=OracleScriptID" json:"oracle_script_id,omitempty"`
	// Calldata is the OBI-encoded calldata bytes available for oracle executor to
	// read.
	Calldata []byte `protobuf:"bytes,3,opt,name=calldata,proto3" json:"calldata,omitempty"`
	// AskCount is the number of validators that are requested to respond to this
	// oracle request. Higher value means more security, at a higher gas cost.
	AskCount uint64 `protobuf:"varint,4,opt,name=ask_count,json=askCount,proto3" json:"ask_count,omitempty"`
	// MinCount is the minimum number of validators necessary for the request to
	// proceed to the execution phase. Higher value means more security, at the
	// cost of liveness.
	MinCount uint64 `protobuf:"varint,5,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	// FeeLimit is the maximum tokens that will be paid to all data source
	// providers.
	FeeLimit github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,6,rep,name=fee_limit,json=feeLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"fee_limit"`
	// RequestKey is the key from request chain to match data source fee payer on
	// Bandchain
	RequestKey string `protobuf:"bytes,7,opt,name=request_key,json=requestKey,proto3" json:"request_key,omitempty"`
	// PrepareGas is amount of gas to pay to prepare raw requests
	PrepareGas uint64 `protobuf:"varint,8,opt,name=prepare_gas,json=prepareGas,proto3" json:"prepare_gas,omitempty"`
	// ExecuteGas is amount of gas to reserve for executing
	ExecuteGas uint64 `protobuf:"varint,9,opt,name=execute_gas,json=executeGas,proto3" json:"execute_gas,omitempty"`
}

func (m *OracleRequestPacketData) Reset()         { *m = OracleRequestPacketData{} }
func (m *OracleRequestPacketData) String() string { return proto.CompactTextString(m) }
func (*OracleRequestPacketData) ProtoMessage()    {}
func (*OracleRequestPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_652b57db11528d07, []int{6}
}
func (m *OracleRequestPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleRequestPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleRequestPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleRequestPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleRequestPacketData.Merge(m, src)
}
func (m *OracleRequestPacketData) XXX_Size() int {
	return m.Size()
}
func (m *OracleRequestPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleRequestPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_OracleRequestPacketData proto.InternalMessageInfo

func (m *OracleRequestPacketData) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *OracleRequestPacketData) GetOracleScriptID() uint64 {
	if m != nil {
		return m.OracleScriptID
	}
	return 0
}

func (m *OracleRequestPacketData) GetCalldata() []byte {
	if m != nil {
		return m.Calldata
	}
	return nil
}

func (m *OracleRequestPacketData) GetAskCount() uint64 {
	if m != nil {
		return m.AskCount
	}
	return 0
}

func (m *OracleRequestPacketData) GetMinCount() uint64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *OracleRequestPacketData) GetFeeLimit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.FeeLimit
	}
	return nil
}

func (m *OracleRequestPacketData) GetRequestKey() string {
	if m != nil {
		return m.RequestKey
	}
	return ""
}

func (m *OracleRequestPacketData) GetPrepareGas() uint64 {
	if m != nil {
		return m.PrepareGas
	}
	return 0
}

func (m *OracleRequestPacketData) GetExecuteGas() uint64 {
	if m != nil {
		return m.ExecuteGas
	}
	return 0
}

// OracleRequestPacketAcknowledgement encodes an oracle request acknowledgement
// send back to requester chain.
type OracleRequestPacketAcknowledgement struct {
	// RequestID is BandChain's unique identifier for this oracle request.
	RequestID uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3,casttype=RequestID" json:"request_id,omitempty"`
}

func (m *OracleRequestPacketAcknowledgement) Reset()         { *m = OracleRequestPacketAcknowledgement{} }
func (m *OracleRequestPacketAcknowledgement) String() string { return proto.CompactTextString(m) }
func (*OracleRequestPacketAcknowledgement) ProtoMessage()    {}
func (*OracleRequestPacketAcknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_652b57db11528d07, []int{7}
}
func (m *OracleRequestPacketAcknowledgement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleRequestPacketAcknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleRequestPacketAcknowledgement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleRequestPacketAcknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleRequestPacketAcknowledgement.Merge(m, src)
}
func (m *OracleRequestPacketAcknowledgement) XXX_Size() int {
	return m.Size()
}
func (m *OracleRequestPacketAcknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleRequestPacketAcknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_OracleRequestPacketAcknowledgement proto.InternalMessageInfo

func (m *OracleRequestPacketAcknowledgement) GetRequestID() uint64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

// OracleResponsePacketData encodes an oracle response from BandChain to the
// requester.
type OracleResponsePacketData struct {
	// ClientID is the unique identifier matched with that of the oracle request
	// packet.
	ClientID string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// RequestID is BandChain's unique identifier for this oracle request.
	RequestID uint64 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3,casttype=RequestID" json:"request_id,omitempty"`
	// AnsCount is the number of validators among to the asked validators that
	// actually responded to this oracle request prior to this oracle request
	// being resolved.
	AnsCount uint64 `protobuf:"varint,3,opt,name=ans_count,json=ansCount,proto3" json:"ans_count,omitempty"`
	// RequestTime is the UNIX epoch time at which the request was sent to
	// BandChain.
	RequestTime int64 `protobuf:"varint,4,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	// ResolveTime is the UNIX epoch time at which the request was resolved to the
	// final result.
	ResolveTime int64 `protobuf:"varint,5,opt,name=resolve_time,json=resolveTime,proto3" json:"resolve_time,omitempty"`
	// ResolveStatus is the status of this oracle request, which can be OK,
	// FAILURE, or EXPIRED.
	ResolveStatus ResolveStatus `protobuf:"varint,6,opt,name=resolve_status,json=resolveStatus,proto3,enum=oracle.v1.ResolveStatus" json:"resolve_status,omitempty"`
	// Result is the final aggregated value encoded in OBI format. Only available
	// if status if OK.
	Result []byte `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *OracleResponsePacketData) Reset()         { *m = OracleResponsePacketData{} }
func (m *OracleResponsePacketData) String() string { return proto.CompactTextString(m) }
func (*OracleResponsePacketData) ProtoMessage()    {}
func (*OracleResponsePacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_652b57db11528d07, []int{8}
}
func (m *OracleResponsePacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleResponsePacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleResponsePacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleResponsePacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleResponsePacketData.Merge(m, src)
}
func (m *OracleResponsePacketData) XXX_Size() int {
	return m.Size()
}
func (m *OracleResponsePacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleResponsePacketData.DiscardUnknown(m)
}

var xxx_messageInfo_OracleResponsePacketData proto.InternalMessageInfo

func (m *OracleResponsePacketData) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *OracleResponsePacketData) GetRequestID() uint64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *OracleResponsePacketData) GetAnsCount() uint64 {
	if m != nil {
		return m.AnsCount
	}
	return 0
}

func (m *OracleResponsePacketData) GetRequestTime() int64 {
	if m != nil {
		return m.RequestTime
	}
	return 0
}

func (m *OracleResponsePacketData) GetResolveTime() int64 {
	if m != nil {
		return m.ResolveTime
	}
	return 0
}

func (m *OracleResponsePacketData) GetResolveStatus() ResolveStatus {
	if m != nil {
		return m.ResolveStatus
	}
	return RESOLVE_STATUS_OPEN
}

func (m *OracleResponsePacketData) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterEnum("oracle.v1.ResolveStatus", ResolveStatus_name, ResolveStatus_value)
	proto.RegisterType((*OracleRequestPacketData)(nil), "oracle.v1.OracleRequestPacketData")
	proto.RegisterType((*OracleRequestPacketAcknowledgement)(nil), "oracle.v1.OracleRequestPacketAcknowledgement")
	proto.RegisterType((*OracleResponsePacketData)(nil), "oracle.v1.OracleResponsePacketData")
}

func init() { proto.RegisterFile("oracle/v1/oracle.proto", fileDescriptor_652b57db11528d07) }

var fileDescriptor_652b57db11528d07 = []byte{
	// 1779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xcd, 0x6f, 0x23, 0x49,
	0x15, 0x4f, 0xdb, 0x9e, 0xc4, 0xfd, 0xec, 0x7c, 0xd5, 0x64, 0x32, 0x1e, 0xef, 0x62, 0x87, 0x68,
	0x41, 0xc3, 0x68, 0xb1, 0xc9, 0x80, 0x10, 0x33, 0xcb, 0x87, 0x62, 0xc7, 0x59, 0x0c, 0xd1, 0x8c,
	0x55, 0x4e, 0x46, 0x80, 0x84, 0x5a, 0xe5, 0xee, 0x8a, 0x53, 0x4a, 0x7f, 0x51, 0xd5, 0x4e, 0xec,
	0xbd, 0x71, 0x43, 0x7b, 0xda, 0x0b, 0x12, 0x97, 0x95, 0x56, 0xe2, 0xc6, 0x15, 0x71, 0xe4, 0xc2,
	0x69, 0x6e, 0xec, 0x09, 0x21, 0x21, 0x79, 0x91, 0xe7, 0x02, 0x7f, 0x00, 0x17, 0xb8, 0xa0, 0xfa,
	0x68, 0x7f, 0x91, 0x65, 0x98, 0xe1, 0xe3, 0xc0, 0x29, 0x7e, 0xbf, 0xf7, 0x5e, 0xf7, 0xfb, 0xf8,
	0xd5, 0xab, 0xd7, 0x81, 0xdd, 0x88, 0x13, 0xd7, 0xa7, 0xf5, 0xab, 0x83, 0xba, 0xfe, 0x55, 0x8b,
	0x79, 0x94, 0x44, 0xc8, 0x36, 0xd2, 0xd5, 0x41, 0x79, 0xa7, 0x1f, 0xf5, 0x23, 0x85, 0xd6, 0xe5,
	0x2f, 0x6d, 0x50, 0xae, 0xf6, 0xa3, 0xa8, 0xef, 0xd3, 0xba, 0x92, 0x7a, 0x83, 0xf3, 0x7a, 0xc2,
	0x02, 0x2a, 0x12, 0x12, 0xc4, 0xc6, 0xe0, 0xde, 0xb2, 0x01, 0x09, 0x47, 0x46, 0x55, 0x71, 0x23,
	0x11, 0x44, 0xa2, 0xde, 0x23, 0x42, 0xbe, 0xb9, 0x47, 0x13, 0x72, 0x50, 0x77, 0x23, 0x16, 0x6a,
	0xfd, 0xfe, 0x5f, 0x2c, 0x80, 0x23, 0x92, 0x90, 0x6e, 0x34, 0xe0, 0x2e, 0x45, 0x3b, 0x70, 0x2b,
	0xba, 0x0e, 0x29, 0x2f, 0x59, 0x7b, 0xd6, 0x7d, 0x1b, 0x6b, 0x01, 0x21, 0xc8, 0x85, 0x24, 0xa0,
	0xa5, 0x8c, 0x02, 0xd5, 0x6f, 0xb4, 0x07, 0x05, 0x8f, 0x0a, 0x97, 0xb3, 0x38, 0x61, 0x51, 0x58,
	0xca, 0x2a, 0xd5, 0x3c, 0x84, 0xca, 0x90, 0x3f, 0x67, 0x3e, 0x55, 0x9e, 0x39, 0xa5, 0x9e, 0xca,
	0x52, 0x97, 0x70, 0x4a, 0xc4, 0x80, 0x8f, 0x4a, 0xb7, 0xb4, 0x2e, 0x95, 0xd1, 0x0f, 0x21, 0x7b,
	0x4e, 0x69, 0x69, 0x75, 0x2f, 0x7b, 0xbf, 0xf0, 0xf0, 0x5e, 0x4d, 0x27, 0x50, 0x93, 0x09, 0xd4,
	0x4c, 0x02, 0xb5, 0x66, 0xc4, 0xc2, 0xc6, 0x97, 0x9e, 0x8f, 0xab, 0x2b, 0xbf, 0xf8, 0xa4, 0x7a,
	0xbf, 0xcf, 0x92, 0x8b, 0x41, 0xaf, 0xe6, 0x46, 0x41, 0xdd, 0x64, 0xab, 0xff, 0x7c, 0x51, 0x78,
	0x97, 0xf5, 0x64, 0x14, 0x53, 0xa1, 0x1c, 0x04, 0x96, 0xcf, 0x7d, 0x9c, 0xfb, 0xd3, 0x47, 0x55,
	0x6b, 0xff, 0xb7, 0x16, 0x14, 0x9f, 0xaa, 0xba, 0x77, 0x55, 0xc0, 0xff, 0xb3, 0xcc, 0x77, 0x61,
	0x55, 0xb8, 0x17, 0x34, 0x20, 0x26, 0x6f, 0x23, 0xa1, 0x47, 0xb0, 0x29, 0x54, 0x0f, 0x1c, 0x37,
	0xf2, 0xa8, 0x33, 0xe0, 0x7e, 0x69, 0x55, 0x1a, 0x34, 0xb6, 0x27, 0xe3, 0xea, 0xba, 0x6e, 0x4f,
	0x33, 0xf2, 0xe8, 0x19, 0x3e, 0xc1, 0xeb, 0x62, 0x26, 0x72, 0xdf, 0x64, 0xf4, 0x2b, 0x0b, 0x00,
	0x93, 0x6b, 0x4c, 0x7f, 0x34, 0xa0, 0x22, 0x41, 0xdf, 0x80, 0x02, 0x1d, 0x26, 0x94, 0x87, 0xc4,
	0x77, 0x98, 0xa7, 0xb2, 0xca, 0x35, 0xde, 0x9c, 0x8c, 0xab, 0xd0, 0x32, 0x70, 0xfb, 0xe8, 0xaf,
	0x0b, 0x12, 0x86, 0xd4, 0xa1, 0xed, 0xa1, 0x63, 0xd8, 0xf0, 0x48, 0x42, 0x1c, 0x13, 0x13, 0xf3,
	0x54, 0x09, 0x72, 0x8d, 0xbd, 0xc9, 0xb8, 0x5a, 0x9c, 0x11, 0x46, 0x3d, 0x63, 0x41, 0xc6, 0x45,
	0x6f, 0x26, 0x79, 0xb2, 0x14, 0x2e, 0xf1, 0x7d, 0x89, 0xa9, 0x4a, 0x15, 0xf1, 0x54, 0x36, 0x71,
	0xff, 0xd8, 0x02, 0x5b, 0xc5, 0x1d, 0x47, 0xfc, 0xdf, 0x0e, 0xfb, 0x0d, 0xb0, 0xe9, 0x90, 0x25,
	0xaa, 0x86, 0x2a, 0xe2, 0x75, 0x9c, 0x97, 0x80, 0x2c, 0x95, 0x6c, 0xe6, 0x5c, 0x1c, 0xb9, 0xb9,
	0x18, 0xfe, 0x9c, 0x85, 0xb5, 0xb4, 0x70, 0x4f, 0x60, 0x4b, 0x1f, 0x48, 0x47, 0x37, 0x74, 0x16,
	0xc6, 0x5b, 0x93, 0x71, 0x75, 0x63, 0x9e, 0x34, 0x2a, 0x94, 0x25, 0x04, 0x6f, 0x44, 0xf3, 0xf2,
	0x62, 0x05, 0x32, 0x8b, 0x15, 0x40, 0x07, 0xb0, 0xc3, 0xf5, 0x6b, 0xa9, 0xe7, 0x5c, 0x11, 0x9f,
	0x79, 0x24, 0x89, 0xb8, 0x28, 0x65, 0xf7, 0xb2, 0xf7, 0x6d, 0x7c, 0x7b, 0xaa, 0x7b, 0x36, 0x55,
	0xc9, 0x0c, 0x03, 0x16, 0x3a, 0x6e, 0x34, 0x08, 0x13, 0x45, 0xae, 0x1c, 0xce, 0x07, 0x2c, 0x6c,
	0x4a, 0x19, 0x7d, 0x0e, 0x36, 0x8c, 0x8f, 0x73, 0x41, 0x59, 0xff, 0x22, 0x51, 0x24, 0xcb, 0xe2,
	0x75, 0x83, 0x7e, 0x5b, 0x81, 0xe8, 0xb3, 0x50, 0x4c, 0xcd, 0xe4, 0x28, 0x51, 0x44, 0xcb, 0xe2,
	0x82, 0xc1, 0x4e, 0x59, 0x40, 0xd1, 0x17, 0xc0, 0x76, 0x7d, 0x46, 0x43, 0x95, 0xfe, 0x9a, 0x22,
	0x62, 0x71, 0x32, 0xae, 0xe6, 0x9b, 0x0a, 0x6c, 0x1f, 0xe1, 0xbc, 0x56, 0xb7, 0x3d, 0xf4, 0x4d,
	0x28, 0x72, 0x72, 0xed, 0x18, 0x6f, 0x51, 0xca, 0xab, 0x83, 0x7b, 0xa7, 0x36, 0x1d, 0x6b, 0xb5,
	0x19, 0x2d, 0x1b, 0x39, 0x79, 0x68, 0x71, 0x81, 0x4f, 0x11, 0x81, 0x8e, 0xa1, 0xc0, 0x7a, 0xae,
	0xe3, 0x5e, 0x90, 0x30, 0xa4, 0x7e, 0xc9, 0xde, 0xb3, 0x96, 0xdc, 0xdb, 0x8d, 0x66, 0x53, 0x2b,
	0x1b, 0x1b, 0x92, 0x09, 0x33, 0x19, 0x03, 0xeb, 0xb9, 0xe6, 0x37, 0xaa, 0x4a, 0xea, 0x50, 0x77,
	0x90, 0x50, 0xa7, 0x4f, 0x44, 0x09, 0x54, 0x6d, 0xc0, 0x40, 0xef, 0x12, 0x61, 0x7a, 0xfd, 0x53,
	0x0b, 0x56, 0x0d, 0xd9, 0xde, 0x04, 0x7b, 0x5a, 0x74, 0x73, 0xee, 0x67, 0x00, 0x7a, 0x00, 0xdb,
	0x2c, 0x74, 0x7a, 0xf4, 0x3c, 0xe2, 0xd4, 0xe1, 0x54, 0x44, 0xfe, 0x95, 0xe6, 0x54, 0x1e, 0x6f,
	0xb2, 0xb0, 0xa1, 0x70, 0xac, 0x61, 0xf4, 0x0e, 0x14, 0x74, 0x0d, 0xe4, 0x73, 0x75, 0xff, 0x0a,
	0x0f, 0x77, 0x96, 0x4b, 0x20, 0x95, 0xa6, 0x02, 0xc0, 0x53, 0x20, 0x8d, 0xeb, 0xd7, 0x59, 0xb8,
	0xab, 0xa9, 0x64, 0x2a, 0xd3, 0x21, 0xee, 0x25, 0x4d, 0xe4, 0xd9, 0x5a, 0xec, 0x86, 0xf5, 0x4f,
	0xbb, 0x71, 0x13, 0x7d, 0x33, 0xff, 0x21, 0xfa, 0x2e, 0x1d, 0x60, 0xc9, 0x45, 0x22, 0x2e, 0x17,
	0xb9, 0x48, 0xc4, 0xa5, 0xe6, 0xe2, 0x02, 0x51, 0x6f, 0x2d, 0x11, 0xf5, 0x02, 0xec, 0x73, 0x4a,
	0x1d, 0x9f, 0x05, 0x2c, 0xf9, 0x6f, 0x4c, 0xfa, 0xfc, 0x39, 0xa5, 0x27, 0xf2, 0xe1, 0x92, 0x15,
	0x29, 0xd7, 0x2f, 0xe9, 0x48, 0x53, 0x19, 0x83, 0x81, 0xbe, 0x4b, 0x47, 0xd2, 0x20, 0xe6, 0x34,
	0x26, 0x5c, 0xd3, 0x26, 0xaf, 0x69, 0x63, 0xa0, 0x77, 0x89, 0x58, 0xe6, 0x95, 0xfd, 0x29, 0xbc,
	0xa2, 0xb0, 0x7f, 0x43, 0xfb, 0x0e, 0xdd, 0xcb, 0x30, 0xba, 0xf6, 0xa9, 0xd7, 0xa7, 0x01, 0x0d,
	0x13, 0xf4, 0x08, 0xd2, 0x77, 0xcf, 0xe6, 0x4a, 0x79, 0x32, 0xae, 0xda, 0xc6, 0x4b, 0xf5, 0x64,
	0x26, 0x60, 0xdb, 0x58, 0xb7, 0x3d, 0xf3, 0x9a, 0xdf, 0x64, 0xa0, 0x94, 0xbe, 0x47, 0xc4, 0x51,
	0x28, 0xe8, 0xeb, 0xf1, 0x64, 0x31, 0x90, 0xcc, 0x2b, 0x04, 0xa2, 0xda, 0x1e, 0x0a, 0xd3, 0xd9,
	0xac, 0x69, 0x7b, 0x28, 0x74, 0x67, 0x97, 0x67, 0x4b, 0xee, 0x1f, 0x67, 0x8b, 0x32, 0x51, 0xe7,
	0x46, 0x9b, 0xdc, 0x4a, 0x4d, 0x14, 0xa6, 0x4c, 0xbe, 0x25, 0x07, 0x99, 0x36, 0x11, 0x09, 0x49,
	0x06, 0x42, 0xcd, 0xa8, 0x8d, 0x87, 0xa5, 0xf9, 0x23, 0xa5, 0x0d, 0xba, 0x4a, 0x2f, 0x47, 0xdc,
	0x9c, 0x28, 0xaf, 0x59, 0x4e, 0xc5, 0xc0, 0x4f, 0x54, 0xc7, 0x8b, 0xd8, 0x48, 0xa6, 0x88, 0xbf,
	0xcb, 0xca, 0x19, 0x20, 0x81, 0xff, 0xbf, 0xa3, 0xb5, 0xd8, 0xd8, 0xd5, 0xd7, 0x6e, 0xec, 0xda,
	0x4b, 0x1a, 0x9b, 0x7f, 0x79, 0x63, 0xed, 0x7f, 0xa5, 0xb1, 0xf0, 0xba, 0x8d, 0x2d, 0xdc, 0xd0,
	0xd8, 0x18, 0x36, 0xa7, 0x77, 0xa5, 0x71, 0x78, 0x03, 0x6c, 0x26, 0x1c, 0xe2, 0x26, 0xec, 0x8a,
	0xaa, 0x06, 0xe7, 0x71, 0x9e, 0x89, 0x43, 0x25, 0xa3, 0xc7, 0x70, 0x4b, 0xb0, 0xd0, 0xd5, 0x73,
	0xbd, 0xf0, 0xb0, 0x5c, 0xd3, 0x9b, 0x74, 0x2d, 0xdd, 0xa4, 0x6b, 0xa7, 0xe9, 0xaa, 0xdd, 0xc8,
	0xcb, 0x21, 0xf4, 0xc1, 0x27, 0x55, 0x0b, 0x6b, 0x17, 0xf3, 0xc6, 0x43, 0xd8, 0xd4, 0xcf, 0x9a,
	0xbe, 0x17, 0x95, 0x60, 0x8d, 0x78, 0x1e, 0xa7, 0x42, 0x98, 0x4b, 0x25, 0x15, 0xe5, 0x92, 0x19,
	0x47, 0xd7, 0x94, 0x6b, 0xda, 0x60, 0x2d, 0xec, 0x3f, 0xcf, 0xc1, 0x6a, 0x87, 0x70, 0x12, 0x08,
	0x74, 0x00, 0x77, 0x02, 0x32, 0x74, 0xe6, 0xee, 0x53, 0xd3, 0x0d, 0x35, 0x29, 0x30, 0x0a, 0xc8,
	0x70, 0x76, 0x99, 0xea, 0xbe, 0xec, 0xc3, 0xba, 0x74, 0x99, 0xb1, 0x45, 0x3f, 0xbb, 0x10, 0x90,
	0xe1, 0x61, 0x4a, 0x98, 0x07, 0xb0, 0x2d, 0x6d, 0x52, 0x76, 0x39, 0x82, 0xbd, 0x47, 0xcd, 0xc9,
	0xdd, 0x0c, 0xc8, 0xb0, 0x69, 0xf0, 0x2e, 0x7b, 0x8f, 0xa2, 0x3a, 0xec, 0xa8, 0x10, 0xd4, 0xe5,
	0xe4, 0xcc, 0xcc, 0x35, 0x09, 0xe5, 0x73, 0xf4, 0xbd, 0x75, 0x94, 0x3a, 0x7c, 0x05, 0x76, 0xe9,
	0x30, 0x66, 0x9c, 0xc8, 0xdd, 0xd7, 0xe9, 0xf9, 0x91, 0x7b, 0xb9, 0x40, 0xcd, 0x9d, 0x99, 0xb6,
	0x21, 0x95, 0x3a, 0xa4, 0xb7, 0x60, 0x43, 0x0e, 0x7a, 0x27, 0xba, 0x26, 0x22, 0x50, 0x83, 0x55,
	0x51, 0x15, 0x17, 0x25, 0xfa, 0x54, 0x82, 0x72, 0xf6, 0x3e, 0x82, 0x7b, 0x31, 0xe5, 0xb3, 0xd5,
	0x68, 0x5a, 0x15, 0xe9, 0xa0, 0x19, 0xba, 0x1b, 0x53, 0x3e, 0xad, 0xbd, 0xa9, 0x8c, 0x74, 0x7d,
	0x1b, 0x90, 0x20, 0x41, 0xec, 0xb3, 0xb0, 0xef, 0x24, 0x7c, 0x64, 0x42, 0xd2, 0xe3, 0x7d, 0x2b,
	0xd5, 0x9c, 0xf2, 0x91, 0x0e, 0xe7, 0x6b, 0x50, 0x32, 0x67, 0x9b, 0xd3, 0x6b, 0xc2, 0x3d, 0x27,
	0xa6, 0xdc, 0xa5, 0x61, 0x42, 0xfa, 0xd4, 0x4c, 0x7c, 0xf3, 0xf9, 0x86, 0x95, 0xba, 0x33, 0xd5,
	0xa2, 0xc7, 0x70, 0x8f, 0x85, 0x9a, 0x5e, 0x4e, 0x4c, 0x43, 0xe2, 0x27, 0x23, 0xc7, 0x1b, 0xe8,
	0x7c, 0xcd, 0x12, 0x72, 0x37, 0x35, 0xe8, 0x68, 0xfd, 0x91, 0x51, 0xa3, 0x16, 0xdc, 0x96, 0xab,
	0x4f, 0x9a, 0x14, 0x0d, 0x49, 0xcf, 0xa7, 0x9e, 0x62, 0x76, 0xbe, 0x71, 0x67, 0x32, 0xae, 0x6e,
	0xb7, 0x1b, 0x4d, 0x93, 0x53, 0x4b, 0x2b, 0xf1, 0x36, 0xeb, 0xb9, 0x8b, 0xd0, 0xe3, 0xfc, 0xcf,
	0x3e, 0xaa, 0xae, 0x28, 0x36, 0xbe, 0x03, 0xa8, 0x43, 0x43, 0x8f, 0x85, 0x7d, 0x73, 0x88, 0x4e,
	0x98, 0x58, 0xb8, 0x03, 0x99, 0x27, 0x49, 0x99, 0x95, 0x37, 0xd8, 0xf4, 0xdc, 0xa7, 0x37, 0xd8,
	0x77, 0x60, 0x6e, 0xb5, 0x42, 0x77, 0x61, 0x4d, 0x31, 0x20, 0x1d, 0x8b, 0x78, 0x55, 0x8a, 0x6d,
	0x0f, 0x7d, 0x06, 0xc0, 0xec, 0x6a, 0xe9, 0x00, 0xb4, 0xb1, 0x6d, 0x90, 0xe9, 0x35, 0xf5, 0x7d,
	0xb8, 0xa3, 0x69, 0x42, 0xb9, 0xe8, 0xcc, 0x35, 0xe8, 0x25, 0x3b, 0xd7, 0x3e, 0xd8, 0x3c, 0x75,
	0x2b, 0x65, 0xe4, 0x16, 0x6c, 0xf6, 0xa5, 0x19, 0xbc, 0xff, 0x07, 0x0b, 0x6e, 0x9b, 0x02, 0x3c,
	0xa3, 0x9c, 0x9d, 0x33, 0x57, 0x17, 0xf3, 0xf3, 0x90, 0x77, 0x2f, 0x08, 0x0b, 0x67, 0x83, 0xbc,
	0x30, 0x19, 0x57, 0xd7, 0x9a, 0x12, 0x6b, 0x1f, 0xe1, 0x35, 0xa5, 0x6c, 0x7b, 0x8b, 0x11, 0x64,
	0x96, 0x23, 0x58, 0x1c, 0x9f, 0xd9, 0x57, 0x19, 0x9f, 0x4b, 0xdf, 0x2e, 0xb9, 0x57, 0xfb, 0x76,
	0x31, 0x85, 0xfb, 0xa5, 0x05, 0x85, 0x0e, 0x67, 0x2e, 0x35, 0xf7, 0x93, 0xfc, 0x5e, 0x1c, 0x05,
	0xbd, 0xc8, 0x4f, 0xbb, 0xa0, 0x25, 0x54, 0x01, 0x08, 0x06, 0x7e, 0xc2, 0x62, 0x9f, 0x4d, 0xe7,
	0xc9, 0x1c, 0x82, 0x36, 0x20, 0x13, 0x0f, 0xcd, 0x19, 0xcf, 0xc4, 0xc3, 0xa5, 0xbc, 0x72, 0xaf,
	0x92, 0xd7, 0xcb, 0xef, 0xeb, 0x07, 0x7f, 0xb3, 0x60, 0x7d, 0x61, 0x6c, 0xa3, 0xaf, 0x43, 0x15,
	0xb7, 0xba, 0x4f, 0x4f, 0x9e, 0xb5, 0x9c, 0xee, 0xe9, 0xe1, 0xe9, 0x59, 0xd7, 0x79, 0xda, 0x69,
	0x3d, 0x71, 0xce, 0x9e, 0x74, 0x3b, 0xad, 0x66, 0xfb, 0xb8, 0xdd, 0x3a, 0xda, 0x5a, 0x29, 0xdf,
	0x7d, 0xff, 0xc3, 0xbd, 0xdb, 0x37, 0x98, 0xa1, 0xaf, 0xc2, 0xee, 0x12, 0xdc, 0x3d, 0x6b, 0x36,
	0x5b, 0xdd, 0xee, 0x96, 0x55, 0x2e, 0xbf, 0xff, 0xe1, 0xde, 0xa7, 0x68, 0x6f, 0xf0, 0x3b, 0x3e,
	0x6c, 0x9f, 0x9c, 0xe1, 0xd6, 0x56, 0xe6, 0x46, 0x3f, 0xa3, 0xbd, 0xc1, 0xaf, 0xf5, 0xbd, 0x4e,
	0x1b, 0xb7, 0x8e, 0xb6, 0xb2, 0x37, 0xfa, 0x19, 0x6d, 0x39, 0xf7, 0x93, 0x9f, 0x57, 0x56, 0x1a,
	0xc7, 0xcf, 0x27, 0x15, 0xeb, 0xe3, 0x49, 0xc5, 0xfa, 0xe3, 0xa4, 0x62, 0x7d, 0xf0, 0xa2, 0xb2,
	0xf2, 0xf1, 0x8b, 0xca, 0xca, 0xef, 0x5f, 0x54, 0x56, 0x7e, 0xf0, 0xf6, 0xdc, 0xc6, 0xda, 0x23,
	0xa1, 0xa7, 0xee, 0x15, 0x37, 0xf2, 0xeb, 0x8a, 0x8c, 0xf5, 0xa1, 0xf9, 0x4f, 0x90, 0xde, 0x5d,
	0x7b, 0xab, 0x4a, 0xfd, 0xe5, 0xbf, 0x07, 0x00, 0x00, 0xff, 0xff, 0x92, 0x7b, 0x4d, 0x7a, 0x2a,
	0x12, 0x00, 0x00,
}

func (this *OracleRequestPacketData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OracleRequestPacketData)
	if !ok {
		that2, ok := that.(OracleRequestPacketData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ClientID != that1.ClientID {
		return false
	}
	if this.OracleScriptID != that1.OracleScriptID {
		return false
	}
	if !bytes.Equal(this.Calldata, that1.Calldata) {
		return false
	}
	if this.AskCount != that1.AskCount {
		return false
	}
	if this.MinCount != that1.MinCount {
		return false
	}
	if len(this.FeeLimit) != len(that1.FeeLimit) {
		return false
	}
	for i := range this.FeeLimit {
		if !this.FeeLimit[i].Equal(&that1.FeeLimit[i]) {
			return false
		}
	}
	if this.RequestKey != that1.RequestKey {
		return false
	}
	if this.PrepareGas != that1.PrepareGas {
		return false
	}
	if this.ExecuteGas != that1.ExecuteGas {
		return false
	}
	return true
}
func (this *OracleRequestPacketAcknowledgement) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OracleRequestPacketAcknowledgement)
	if !ok {
		that2, ok := that.(OracleRequestPacketAcknowledgement)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RequestID != that1.RequestID {
		return false
	}
	return true
}
func (this *OracleResponsePacketData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OracleResponsePacketData)
	if !ok {
		that2, ok := that.(OracleResponsePacketData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ClientID != that1.ClientID {
		return false
	}
	if this.RequestID != that1.RequestID {
		return false
	}
	if this.AnsCount != that1.AnsCount {
		return false
	}
	if this.RequestTime != that1.RequestTime {
		return false
	}
	if this.ResolveTime != that1.ResolveTime {
		return false
	}
	if this.ResolveStatus != that1.ResolveStatus {
		return false
	}
	if !bytes.Equal(this.Result, that1.Result) {
		return false
	}
	return true
}

func (m *OracleRequestPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleRequestPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleRequestPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExecuteGas != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.ExecuteGas))
		i--
		dAtA[i] = 0x48
	}
	if m.PrepareGas != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.PrepareGas))
		i--
		dAtA[i] = 0x40
	}
	if len(m.RequestKey) > 0 {
		i -= len(m.RequestKey)
		copy(dAtA[i:], m.RequestKey)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.RequestKey)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.FeeLimit) > 0 {
		for iNdEx := len(m.FeeLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOracle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.MinCount != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.MinCount))
		i--
		dAtA[i] = 0x28
	}
	if m.AskCount != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.AskCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Calldata) > 0 {
		i -= len(m.Calldata)
		copy(dAtA[i:], m.Calldata)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.Calldata)))
		i--
		dAtA[i] = 0x1a
	}
	if m.OracleScriptID != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.OracleScriptID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ClientID) > 0 {
		i -= len(m.ClientID)
		copy(dAtA[i:], m.ClientID)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.ClientID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OracleRequestPacketAcknowledgement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleRequestPacketAcknowledgement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleRequestPacketAcknowledgement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestID != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.RequestID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OracleResponsePacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleResponsePacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleResponsePacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ResolveStatus != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.ResolveStatus))
		i--
		dAtA[i] = 0x30
	}
	if m.ResolveTime != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.ResolveTime))
		i--
		dAtA[i] = 0x28
	}
	if m.RequestTime != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.RequestTime))
		i--
		dAtA[i] = 0x20
	}
	if m.AnsCount != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.AnsCount))
		i--
		dAtA[i] = 0x18
	}
	if m.RequestID != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.RequestID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ClientID) > 0 {
		i -= len(m.ClientID)
		copy(dAtA[i:], m.ClientID)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.ClientID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintOracle(dAtA []byte, offset int, v uint64) int {
	offset -= sovOracle(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *OracleRequestPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientID)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	if m.OracleScriptID != 0 {
		n += 1 + sovOracle(uint64(m.OracleScriptID))
	}
	l = len(m.Calldata)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	if m.AskCount != 0 {
		n += 1 + sovOracle(uint64(m.AskCount))
	}
	if m.MinCount != 0 {
		n += 1 + sovOracle(uint64(m.MinCount))
	}
	if len(m.FeeLimit) > 0 {
		for _, e := range m.FeeLimit {
			l = e.Size()
			n += 1 + l + sovOracle(uint64(l))
		}
	}
	l = len(m.RequestKey)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	if m.PrepareGas != 0 {
		n += 1 + sovOracle(uint64(m.PrepareGas))
	}
	if m.ExecuteGas != 0 {
		n += 1 + sovOracle(uint64(m.ExecuteGas))
	}
	return n
}

func (m *OracleRequestPacketAcknowledgement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestID != 0 {
		n += 1 + sovOracle(uint64(m.RequestID))
	}
	return n
}

func (m *OracleResponsePacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientID)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	if m.RequestID != 0 {
		n += 1 + sovOracle(uint64(m.RequestID))
	}
	if m.AnsCount != 0 {
		n += 1 + sovOracle(uint64(m.AnsCount))
	}
	if m.RequestTime != 0 {
		n += 1 + sovOracle(uint64(m.RequestTime))
	}
	if m.ResolveTime != 0 {
		n += 1 + sovOracle(uint64(m.ResolveTime))
	}
	if m.ResolveStatus != 0 {
		n += 1 + sovOracle(uint64(m.ResolveStatus))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	return n
}

func sovOracle(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOracle(x uint64) (n int) {
	return sovOracle(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *OracleRequestPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleRequestPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleRequestPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleScriptID", wireType)
			}
			m.OracleScriptID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleScriptID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Calldata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Calldata = append(m.Calldata[:0], dAtA[iNdEx:postIndex]...)
			if m.Calldata == nil {
				m.Calldata = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskCount", wireType)
			}
			m.AskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCount", wireType)
			}
			m.MinCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeLimit = append(m.FeeLimit, types.Coin{})
			if err := m.FeeLimit[len(m.FeeLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareGas", wireType)
			}
			m.PrepareGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteGas", wireType)
			}
			m.ExecuteGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecuteGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleRequestPacketAcknowledgement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleRequestPacketAcknowledgement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleRequestPacketAcknowledgement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestID", wireType)
			}
			m.RequestID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleResponsePacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleResponsePacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleResponsePacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestID", wireType)
			}
			m.RequestID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnsCount", wireType)
			}
			m.AnsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AnsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestTime", wireType)
			}
			m.RequestTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolveTime", wireType)
			}
			m.ResolveTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolveTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolveStatus", wireType)
			}
			m.ResolveStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolveStatus |= ResolveStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result[:0], dAtA[iNdEx:postIndex]...)
			if m.Result == nil {
				m.Result = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipOracle(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOracle
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOracle
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOracle
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOracle        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOracle          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOracle = fmt.Errorf("proto: unexpected end of group")
)
